### ISSUE TITLE
Custom OPA Rules

### ISSUE THREAD

**Issue by ssnmworld** [kubescape/kubescape#1042]
## Overview
 Is it possible to create our custom rego rules and use it for scanning ?

**Comment by dwertent** [comment]
Hi @ssnmworld and thank you for asking.
In general, the answer is yes. You can write manually a control, add the control to a framework, and scan using the `--use-from` flag. That being said, I do not recommend doing so because we do not have it documented and the flow is tedious.  
Unfortunately, we do not have it documented and out-of-the-box support because we are working on other interesting features. But this is in our roadmap :) 

Maybe @yuleib can assist you here.

**Comment by Shreyas220** [comment]
can i work on this?

**Comment by dwertent** [comment]
Yes, it is documented [here](https://github.com/kubescape/regolibrary/blob/master/README.md#add-a-control) how to write a custom control.

I [explained here](https://github.com/kubescape/kubescape/issues/1042#issuecomment-1386694612) how to run the custom control.

We would have a better integration with custom controls in the future :)
