### ISSUE TITLE
LFX proposal: Store Kubescape configuration scan results as CRs

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1225]
This issue relates to a **proposal** for a [LFX mentorship project](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/02-Jun-Aug) for Term 2, 2023.  It has not yet been accepted. Please feel free to comment on this issue about how we might improve the proposal, but commenting here is not the same as applying to LFX.

- Description: [Kubescape](http://kubescape.io/) is a utility that can scan a Kubernetes cluster and report on its security posture. There is an "operator" which can be installed in the cluster to perform scheduled scans scan, but this is largely used to send the data to an external service. In this project, you will implement a mechanism in the Kubescape operator to save scan results locally in a custom resource (CR), as well as a watch so that scans can be performed on cluster state changes.
- Expected Outcome: Having the ability to scan a cluster when it changes, and have the results saved inside the cluster. This will allow users and automations to judge the security posture of changes that are made to the cluster (for example, deployments or rollouts.)
- Recommended Skills: Go
- Mentors:
  - Ben Hirschberg (@slashben, ben AT armosec.io)
  - Craig Box (@craigbox, craigb AT armosec.io)
  - David Wertenteil (@dwertent, dwertent AT armosec.io)

**Comment by manulpatel** [comment]
Hello @craigbox! I am new to Kubescape. I would like to develop this new functionality as a part of the LFX Mentorship. Could you please give little hint on where should I get started, apart from local dev setup and familiarising myself with the codebase and community.

**Comment by craigbox** [comment]
Those are good steps.  If the proposal is accepted, we will look for applications that show an understanding of both the platform and the codebase, as well as excellent communication skills.

**Comment by nishchay-veer** [comment]
Hey @craigbox  are the applications open for LFX mentorship ?

**Comment by craigbox** [comment]
I believe they open today.  You'll use the LFX platform; I'm not sure when the projects will be loaded.

https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/README.md#program-guidelines is your go-to.

**Comment by money8203** [comment]
Hey @craigbox,

I'd love to work on this project as a part of LFX mentorship . As a Go developer, I believe this project will be a great opportunity for me to apply my skills and gain hands-on experience in Kubernetes security. Looking forward to working with the Kubescape team and contributing to the project's success. 

In the meantime I'll explore the kubescape project and go through the documentation and good first issues!

**Comment by kr-2003** [comment]
Hey @craigbox @slashben @dwertent,
I am new to open source and is currently have experience with Docker, Kubernetes, Gitlab CI/CD and AWS. I am also currently learning GoLang. I would love to contribute under LFX mentorship. Can you please help me on how to contribute to this project?? For example, what should I do after cloning the project? How should I test the changes that I make??

**Comment by craigbox** [comment]
Thank you to everyone who is interested in this issue.  Applications must be made to [the LFX page](https://github.com/cncf/mentoring/blob/main/programs/lfx-mentorship/README.md#program-guidelines) (not this issue!) by Tue May 23, 5:00 PM PDT.

Unfortunately, we can't give everyone specifics on how to contribute to the project, provide resources, or answer general questions on "how to code", before the mentees are selected. Getting over that first hurdle of looking at the documentation and finding out how to ask good questions is considered a prerequisite for the project.  A good application will demonstrate an understanding of the space gained from your own research.  A great application will have done that research and updated the "how to contribute to Kubescape" guide with your learnings!

**Comment by Abinash-bit** [comment]
Hey , @craigbox  as the issue is not closed yet , I have the following idea to work on this issue .

### Step 1 : To store Kubescape configuration scan results as Custom Resources (CRs), we can create a Kubernetes CRD (Custom Resource defination) that defines the structure of the CRs. Once the CRD is created, we can create individual CRs based on the scan results and store them in the Kubernetes cluster.

### Define the CRD: We Should Create a YAML file that defines the structure of the CRD. This file should specify the metadata, schema, and validation rules for the CRs. Let's Say 

`# kubescape-crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubescapes.myname.com
spec:
  group: myname.com
  version: v
  names:
    kind: Kubescape
    plural: kubescapes
    singular: kubescape
    shortNames:
    - ks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        scanResult:
          type: string
        severity:
          type: string
        resource:
          type: string
`
### Step 2 :

### We should Apply the CRD :

`kubectl apply -f kubescape-crd.yaml
`
###  Step 3 - Creating CRs: Based on the scan results, creating individual CRs using the defined CRD structure. We can generate CRs programmatically based on the scan results or manually create them using YAML files.

`# kubescape-cr.yaml
apiVersion: mycompany.com/v1
kind: Kubescape
metadata:
  name: kubescape-result-1
spec:
  scanResult: "Failed"
  severity: "High"
  resource: "deployment/my-app"
`
### Step - 4 : Creating the CR by applying the YAML file:

`kubectl apply -f kubescape-cr.yaml
`
###  Once the CRs are created, We can query and manage them using kubectl commands:

`**kubectl get kubescapes
**`
`**kubectl get kubescape kubescape-result-1 -o yaml
 **`

**Comment by craigbox** [comment]
@Abinash-bit Thanks; we're actually working on this internally at ARMO as part of the Kubescape 3.0 project.
