### ISSUE TITLE
Can I run a kubescape ARMO platform server on my own?

### ISSUE THREAD

**Issue by tymaoa2** [kubescape/kubescape#1354]
The UI interface is really good, however for the business privacy, my company couldn't upload the scan result to the public server (air-gapped enviroment), could I build the platform on my own ?

**Comment by dwertent** [comment]
Hi @tymaoa2 , Thank you for your compliment, I'm glad you enjoy Kubescape and the ARMO platform :)
The ARMO platform is not open-sourced, therefore you cannot run in an air-gapped environment.

However, ARMO has an offering for air-gapped environments, please contact @GibliX / @yossi77 for more information.

**Comment by clouddork** [comment]
Tymoa2...I am ARMO's Solutions Architect. Use the following link to schedule some time with me and we can discuss your requirements: https://usemotion.com/meet/cloudDork/meeting?d=30

**Comment by craigbox** [comment]
There are two things we are working on in this space:

* In the next few weeks we will be fully documenting the API used to talk to a Kubescape-compatible backend, so that someone could integrate Kubescape with their own services similarly to how ARMO has. 
* In the next 6 months we'll be working on an in-cluster web interface which shows you the state of your current cluster.
