### ISSUE TITLE
Unable to see print statement output added in rego policy

### ISSUE THREAD

**Issue by SubhadeepSen** [kubescape/kubescape#1361]
Hi Team

I am trying to create a custom framework. I'm trying to some info when the rego policy is executed. I have added some print statements in the rego policy but I'm not able to find a way to get this info. Could anyone please help.

**Comment by dwertent** [comment]
@YiscahLevySilas1 What do you think?

**Comment by SubhadeepSen** [comment]
Can I use kubescape to run framework (custom framework) on any YAML file (not Kuberneters YAML) ?

**Comment by dwertent** [comment]
@SubhadeepSen What are you trying to achieve by this? Kubescape is for scanning Kubernetes-related resources, If you are looking to write and run rego controls using OPA that are not related to Kubernetes, Kubescape is not the right "control executer" for you :)

If you wish to write a custom control, you can try to follow the documentation [here](https://github.com/kubescape/regolibrary/blob/master/README.md#add-a-control).

Just that we use the same terminology - a framework is a group of controls, so you can use custom frameworks with Kubescape but it is mainly for deciding what controls should run and what should not.

**Comment by SubhadeepSen** [comment]
@dwertent I got the above question somehow in my mind. Thank you for the clarification :-) I have tried writing a custom framework as suggested and I'm able to execute it. The only I faced while debugging my rego policy is that, I was not able to get the output of print() statement added in rego policy.

I'll definitely explore OPA to understand it better and to see how it fits my use cases. Would you mind suggesting any framework which I can use for validating terraform resources if you are aware of any.

**Comment by dwertent** [comment]
Regarding printing from the rego, I asked @YiscahLevySilas1 to take a look into it (I think she is on vacation).
About validating terraform- Kubescape is a scanner for misconfigurations and vulnerabilities, but does not validate the yaml files or any other formats.

We had many internal discussions about this, but we have not yet added validating capabilities.

cc @rotemamsa @craigbox

**Comment by YiscahLevySilas1** [comment]
Hi @SubhadeepSen , in order to use see the print messages from your rego you need to enable it, we don't do so in kubescape to avoid "noisy" debug messages, but you can do it in one of these ways:
1. in Kubescape, change the [compilation of rego modules](https://github.com/kubescape/kubescape/blob/26c47d501c11256e9f1b819471e1c8410ba7d728/core/pkg/opaprocessor/processorhandler.go#L300) to:
`compiled, err := ast.CompileModulesWithOpt(modules, ast.CompileOpts{
		EnablePrintStatements: true,
	})`
2. You can [run a single rego](https://github.com/kubescape/regolibrary/blob/10bbaf7166a2689c7da45a860689a9c8c3e2d8b5/testrunner/README.md?plain=1#L20) for debug puposes using the [Test-Runner](https://github.com/kubescape/regolibrary/blob/10bbaf7166a2689c7da45a860689a9c8c3e2d8b5/testrunner/README.md?plain=1#L20) in regolibrary
Feel free ro reach out if you need more help, good luck!
