### ISSUE TITLE
snap store needs updating

### ISSUE THREAD

**Issue by craigbox** [kubescape/kubescape#1387]
https://snapcraft.io/kubescape

* lists @HollowMan6 as developer, not Kubescape
* lists armosec.io as URL, not kubescape.io
* only `edge` has the latest build: how do we make this filter down?

<img width="785" alt="Screenshot 2023-09-12 at 1 30 07 PM" src="https://github.com/kubescape/kubescape/assets/132510/18c15627-b416-46c0-a974-bb3163181b54">

/cc @HollowMan6

**Comment by HollowMan6** [comment]
> * lists @HollowMan6 as developer, not Kubescape

Since I uploaded that package, it shows my name. I'm not sure if there's any way to transfer the ownership (don't think they have the option, only adding collaboration).

> * lists armosec.io as URL, not kubescape.io

Updated.

> * only `edge` has the latest build: how do we make this filter down?

You need to manually go to https://snapcraft.io/kubescape/releases and change the channel release version. This process can't be automated. I just helped update everything to 2.9.0

![image](https://github.com/kubescape/kubescape/assets/43995067/3157629c-5463-48a5-a01d-104923630a24)

**Comment by matthyx** [comment]
looks like we're updated, thanks @HollowMan6 !
