### ISSUE TITLE
C-0211 is suggesting an invalid value for sysctls

### ISSUE THREAD

**Issue by javsalgar** [kubescape/kubescape#1582]
# Description
When running C-0211 in a workload that does not have sysctls or supplementalGroups set in their securityContext section, the scan fails with the following error:

```
│ Severity             : High                                                                          │
│ Control Name         : CIS-5.7.3 Apply Security Context to Your Pods and Containers                  │
│ Docs                 : https://hub.armosec.io/docs/c-0211                                            │
│ Assisted Remediation : 
│                        spec.template.spec.securityContext.sysctls=1                                  │
│                        spec.template.spec.securityContext.supplementalGroups=YOUR_VALUE              │
```

If I try setting sysctls=1 in my security context it will fail 

```
        * Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field PodSecurityContext.spec.template.spec.securityContext.sysctls of type []v1.Sysctl
```

What is more, it is not clear to me (looking at the CIS Docker Benchmark or similar) what it is expected from us to set in the sysctls section if we don't have specific needs on that. The same with supplementalGroups, if the only group that I use is the one defined in `fsGroup`.  In order to bypass that I'm tempted to set the same group id inside the supplementalGroups section, but I don't see much value there.

# Environment
OS: `Ubuntu 22,04 ` 
Version: ` 3.0.3` 
 
# Steps To Reproduce

1. Deploy a sample chart, such as bitnami/postgresql
2. Run 'kubescape scan control c-0211 --verbose
3. See error

# Expected behavior
A clear solution path on how to fix the potential vulnerability reported

# Actual Behavior
An incorrect value to set in my YAML that causes the deployment to fail

# Additional context

**Comment by YiscahLevySilas1** [comment]
Hi @javsalgar - thanks for reporting this! It's indeed a mistake in the suggestion and we'll work on fixing it.
I agree that it's not very clear what the required settings of each section in the security context should be according to the CIS benchmark. We tried to give suggestions where possible but like you mentioned, it depends very much on the needs of each specific workload. That's why in this case (and in most cases where we supply assisted remediation) - I would suggest to always preform a manual review of the suggestions before applying them to make sure they address your needs and use exceptions where you think your yaml is configured correctly.
