### ISSUE TITLE
Introduce `sensitiveKeyNamesAllowed` parameter

### ISSUE THREAD

**Issue by RomanTheLegend** [kubescape/kubescape#1588]
## Overview
Currently only **_values_** could be excluded from control-inputs by specifying `sensitiveValuesAllowed` variable. At the same time it should be possible to exclude key names that act as secret references but not as secrets themselves.

For example, an env variable called `VAULT_SECRET_PATH` would be flagged as an issue, while in reality it may contain only a path to the actual secret in Vault. 
Modifying `sensitiveKeyNames` list is not an option because I'd still want to see other improper uses of keyword `secret` 

## Solution

Introduce a new parameter called `sensitiveKeyNamesAllowed` that would act as `sensitiveValuesAllowed` but for key names

## Workaround
I couldn't find this in the code, but seems like `sensitiveKeyNames` is using regexp for string matching, so maybe it would be possible just to use escape characters to narrow the scope for certain keywords? For example, `secret$` for looking for `secret` keyword only at the end of variable name?

**Comment by ShivamJha2436** [comment]
Assign me this issue, I'm working on this.

**Comment by YiscahLevySilas1** [comment]
This issue was resolved in [this PR](https://github.com/kubescape/regolibrary/pull/581) in regolibrary. We now have `sensitiveValuesAllowed` and `sensitiveKeyNamesAllowed` that allow excluding values and key names from failing, respectively.
In the example above of `VAULT_SECRET_PATH` one would be able to configure `sensitiveKeyNamesAllowed` to include `VAULT_SECRET_PATH` or even `_PATH` therby preventing false positives.
