### ISSUE TITLE
Update documentation and usages to remove libgit usage 

### ISSUE THREAD

**Issue by jayantpranjal0** [kubescape/kubescape#1687]
## Overview
Kubescape no longer requires libgit to be built, but it remains to be updates some places in the documentation and some usages such as KillerCoda scenario. 

## Solution
Identify and update wherever libgit have been mentioned or used

**Comment by coderquill** [comment]
Hello @jayantpranjal0 , @matthyx 
I am Rupali. I was exploring this issue, and I cant find any usages of the libgit library in the documentation, except for in the [build](https://github.com/kubescape/kubescape/wiki/Building#build-on-linuxmacos) part of the wiki, which is referenced in the contributing.md file. I believe I dont have access to update the wiki here.

For the KillerCoda scenario, you are right, and it does produce `make: *** No rule to make target 'libgit2'.  Stop.`. I was curious if the config file to create the scenario (again, referenced in the [build](https://github.com/kubescape/kubescape/wiki/Building#build-kubescape-in-a-pre-configured-playground) section of the wiki) is stored somewhere. So that we can remove the reference to libgit from there.

Would love some guidance to complete this. Please let me know if I am missing something obvious. Thank you!

**Comment by matthyx** [comment]
@coderquill thanks I've edited the page on wiki
@suhasgumma can you update the Killercoda scenario?

**Comment by coderquill** [comment]
Awesome! 
@matthyx @suhasgumma If needed, I can help in updating the Killercoda scenario/creating a new one. lmk. Thanks!

**Comment by arujjval** [comment]
Is this issue still open?

**Comment by matthyx** [comment]
not until the Killercoda has been updated
