### ISSUE TITLE
use kubescape problem

### ISSUE THREAD

**Issue by loxiaopohaiol** [kubescape/kubescape#1721]
when I first run this commond on a kubernetes cluster master host : "kubescape scan framework nsa --kubeconfig /root/.kube/config"
show that:
![image](https://github.com/user-attachments/assets/b0ca5cd0-fb1e-49d2-8ce3-9df5292ce684)

Why is the content of the table different from the presentation of the examples in the explanatory document, and my content looks very messy
and What do the two alarms mean at the end? Do I have to install kubescape operator? Otherwise can't scan k8s?

**Comment by loxiaopohaiol** [comment]
And have another question, when I install the kubescape operator through the offical user manul, all pod running:
![image](https://github.com/user-attachments/assets/a2b66ae6-c393-4c88-82e4-c7b485848b98)
but, I can't see any resources about the kubescape operator make:
![image](https://github.com/user-attachments/assets/2fc78bd2-ed19-43f4-b3d2-245145dc11ae)

how can I do next?I want to see the Scan results.

**Comment by dwertent** [comment]
@loxiaopohaiol, thanks for raising these points! I'll address them below:

1. In the CLI, there are two different views when scanning a cluster: 
   - **Cluster-wide view** (the default): This provides a summary of the cluster's configurations and resources.
   - **Framework-specific view**: This focuses on the results based on the controls for the specific framework being scanned.  
   The example you mentioned shows the cluster-wide summary view. However, since you ran the scan with a specific framework, you received the framework-specific controls view.

2. The alarms at the end indicate that the scan wasn't fully comprehensive. When using the CLI, some controls can be scanned, but to get a full report for your cluster, you'll need to install the Helm chart.

3. Regarding your [second comment](https://github.com/kubescape/kubescape/issues/1721#issuecomment-2264876135), do you have any other resources running in the cluster? By default, the Kubescape and `kube-system` namespaces are excluded from scans, so if there are no other resources, it's possible nothing was scanned.

**Comment by matthyx** [comment]
closing for lack of information
