### ISSUE TITLE
3rd party container registry integration

### ISSUE THREAD

**Issue by tks98** [kubescape/kubescape#287]
Hello Kubescape team, 

I received an email outlining some contribution areas for Kubescape. I specifically saw an ask for integrations with 3rd party container registry APIs and vulnerability scan results. 

Recently I have been doing a lot of development work with the Harbor container registry https://goharbor.io, specifically utilizing their APIs to create tools which trigger and analyze vulnerability scan results. 

I have a few ideas for integrations that may be useful, however, I am not 100% sure what kinds of integrations you are looking for specifically. 

Triggering image scans and retrieving scan results are not unique to Harbor, it is also available in several other container registries. Perhaps this could be a starting point to outline an interface for other contributors to add support for other registries? 

These are the initial ideas I had for integrations which I feel could be useful. Results would be in JSON and used for either local consumption or submission to armo cloud. 

**Registry Login**

- `kubescape registry login https://myharborregistry.com`

**Trigger a vulnerability scan of a single image (or all images) and/or retrieve the scan results** 

- `kubescape registry scan  --images https://myharborregistry.com/project/repo/image@sha256xxxxxxx`
- `kubescape registry scan all`

**Search registry images for specified vulnerabilities and retrieve a report of images that contain them**
- `kubescape registry search --cves CVE-2021-44228,CVE-2021-25742`

**Generate an image vulnerability report for images in their harbor instance. Show CVSS score statistics for images. Similar to the Kubescape scan results, but for image(s) CVE's**
- `kubescape registry generate-summary`

Please let me know if these types of integrations could be useful, or if the team had other ideas as to how 3rd party container registries could be utilized. Happy to help where I can. Thanks!

**Comment by slashben** [comment]
Hi @tks98 

You made an impressive discussion starter :)

First, I'd like to give an answer of "why" to integrate Kubescape with container registries.

1. We are planning to create controls which take into account image vulnerabilities, example: looking for public internet facing workloads with critical vulnerabilities. These are seriously effecting the security health of a cluster and therefore we think it is important to cover it. We think that most container registries are/will support image scanning like Harbor and therefore the ability to get information from them is important. 
2. There are information in the image repository which is important for existing controls as well. They are incomplete without it, example see this issue: #19 . These are not necessarily image vulnerability related. Can be information in the image manifest (like the issue before), but it can be the image BOM related.

> Perhaps this could be a starting point to outline an interface for other contributors to add support for other registries?

You have a valid point about interoperation and extensibility. At the first step, we would like to define this interface.

I suggest the interface should cover the following high level functionality:
* Authentication against the information source (abstracted login)
* Triggering image scan
* Reading image scan status (with last scan date and etc.)
* Getting vulnerability information for a given image 
* Getting images for a given vulnerability
* Getting image information (like manifest)

The implementation of this interface should be able to work with other implementations, since Kubescape will see multiple image sources in a single cluster.

Please comment. (you can also find us on our Discord channel, if you want more interactive responses :) )

@Bezbran @dwertent , we will need to think how will we connect OPA/Rego-s to this interface.

Cheers

**Comment by tks98** [comment]
Thanks for the quick reply @slashben! I think the high level functionality outlined here makes a lot of sense for 3rd party registry integration. I'll message the discord with further questions as I start implementing these for harbor.

**Comment by slashben** [comment]
@tks98 

Please check out https://github.com/armosec/kubescape/blob/dev/docs/proposals/container-image-vulnerability-adaptor.md 

Comments are welcome!

**Comment by slashben** [comment]
@tks98 

We have done some progress and developing the first adaptor implementation. It is still in our own branches but it will be published in `dev` branch by the end of week.
(preview: https://github.com/slashben/kubescape/tree/master/container-images)

**Comment by tks98** [comment]
@slashben Thanks for the update! Once the adaptor implementation is finalized I can adjust my harbor adaptor to fit that spec. So far have the ability to authenticate, trigger scans, and receive vulnerability information for images in the harbor registry.

**Comment by dwertent** [comment]
We have decided to remove the adaptors from Kubescape. 
Kubescape will support scanning the image directly.
