### ISSUE TITLE
Override name of the currently scanned cluster

### ISSUE THREAD

**Issue by vladklokun** [kubescape/kubescape#613]
**Is your feature request related to a problem? Please describe.**
When I use Kubescape to scan a cluster, I would like to use a custom name for the cluster I am scanning instead of a name that Kubescape determines automatically.

**Describe the solution you'd like**
I would like a CLI flag that allows me to set a name for the cluster. Perhaps, like this:
```
kubescape scan --clusterName=myFancyCluster
```

The cluster name should:
- NOT include special characters
- contain less than 256 characters

**Additional context**
Kubescape Helm charts currently validate cluster names via the following [pipeline](https://github.com/armosec/armo-helm/blob/c5cde62b09c3b23b33e2360eccadfe4dc1d70060/charts/armo-components/templates/armo-kubescape-configmap.yaml#L16):
```
{{ regexReplaceAll "\\W+" .Values.clusterName "-" | lower  }}
```

**Comment by octonawish-akcodes** [comment]
I can work on this

**Comment by shubhzhs** [comment]
@vladklokun can you assign me please

**Comment by vladklokun** [comment]
@octonawish-akcodes you’ve got first dibs, so feel free to go ahead :)

@shubhzhs @sahilsuman933 @rghdrizzle we appreciate your desire to help, so please check out [other issues](https://github.com/kubescape/kubescape/issues?q=is%3Aissue+is%3Aopen+label%3A%22open+for+contribution%22) that are open for contributing :handshake:

**Comment by sahilsuman933** [comment]
Sure @vladklokun

**Comment by nashetali837** [comment]
Hey, In can work on n this

**Comment by anubhav06** [comment]
Hi @vladklokun. I was trying to understand the issue.

Let's say I have multiple clusters running. Should this CLI flag, help me in choosing which cluster to scan? 
`For Example:`
cluster-1-name: *development*
cluster-2-name: *production*
Running `kubescape scan --clusterName=development` would scan the 1st cluster instead of 2nd.

**OR**
  
The CLI flag should just help in setting a custom name for the automatically determined cluster name by Kubescape (original cluster name).
`For Example:` 
cluster-1-name: *development*
Running `kubescape scan --clusterName=testing-development` would show the cluster's name as `"testing-development"` while showing the Kubescape results in the terminal and cloud.

**Comment by dwertent** [comment]
Merged
