### ISSUE TITLE
Adding issue forms to the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [kubescape/kubescape#685]
I want to add a few issue forms so that it will be convenient for new contributors to open issues. There are already issue templates for this project but they are deprecated now, issue forms instead work way better. I plan to create  **Bug Report**, and **Feature Request** forms. 

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**
- **Urgency indicator**
- **Desktop Info (OS, Version, Browser, etc):**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Comment by SrijanShovit** [comment]
Hi @dwertent I would like to contribute in this issue ,Could you please share resources that so as to understand this issue and start contributing asap

**Comment by vladklokun** [comment]
Hi! Thanks for taking an interest in contributing to Kubescape :)

As far as I know, issue templates are not deprecated at the moment, while issue forms are in beta. Still, they do look fancy, and we can try them out. So please, go ahead.

> The Bug Report issue form will have the following fields
> - Description of the bug
> - How to Reproduce
> - Expected behavior
> - Urgency indicator
> - Desktop Info (OS, Version, Browser, etc):

At the moment, we triage the tickets on our own, so we don’t need the Urgency Indicator field. Also, to understand the user’s problem, it helps us to know what is the actual result they get, so please include the Actual Result field. So, in the end, the form should use the same exact fields that the current issue templates use. At the moment, these are:
- Describe the bug
- Environment
- Steps to reproduce
- Expected behavior
- Actual behavior
- Additional context

**Comment by MonarchGitHub** [comment]
Okay, got it 👍
