### ISSUE TITLE
Output table does not fit in my terminal

### ISSUE THREAD

**Issue by dwertent** [kubescape/kubescape#933]
# Describe the bug
I am running `kubescape scan -v` and the printed table is to wide for my termianl

# Environment
OS: Mac, M1
Version: the version that Kubescape reports when you run `kubescape version`
```
Your current version is: v2.0.176
```

# Steps To Reproduce
run `kubescape scan -v`

# Expected behavior
A nice and readable table 

# Actual Behavior
A non-readable table 

# Additional context
The table should be rendered so it will match the default terminal width of 80 columns

**Comment by matthyx** [comment]
@dwertent I have played a bit with the current table lib... wrapping is weird in its workings and I don't have something satisfying for an 80 col terminal.
Since the project is pretty outdated, I suggest trying a quick PoC with https://github.com/jedib0t/go-pretty/blob/main/table/README.md and see how far it goes?
If you want I can work on that during breaks.

**Comment by dwertent** [comment]
@matthyx Thank you for taking a look into it.
Sure, if you find a package that will suit us better, feel free to open a PR.

Just make sure that it looks good also when running with the `--verbose` flag.

**Comment by fredbi** [comment]
@matthyx hello. I've played a bit on that issue and I've also been looking into the package you're mentioning. From what I could get, go-pretty doesn't have the concept of "wrapping cells into multiple lines" (like "tablewriter"), and columns just get truncated. Apparently, we may hack into this by injecting a custom "widthEnforcer". Perhaps you could manage it this way.

On my side, I've been working a bit on improving "tablewriter" to support wrapping based on the constraint of a row of a limited size. There is a lot to do, since this  package is so old...

**Comment by matthyx** [comment]
As you wish @fredbi I haven't started any concrete work on this issue.
Maybe there are other packages that could help us, such as https://charm.sh/ ?

**Comment by fredbi** [comment]
Yes, perhaps this is a good lead.
Rendering tables nicely is definitely not an easy task. The guys who did the LaTeX tabular macros were definitely giants! 
Let's experiment for a while. I'll keep you posted here with any findings.

**Comment by fredbi** [comment]
@matthyx as promised an update about this topic.
I've rewritten almost in full the tablewriter library in `github.com/fredbi/tablewriter`.
Besides a lot of refactoring (not fully complete yet) I've added the feature we are missing: self-adapting the table under a global width constraint. It also breaks words that are too long, but that's still a bit ugly. 
I am currently testing the integration in the kubescape printers.

**Comment by XDRAGON2002** [comment]
Hi @fredbi @matthyx!
Is help needed on this? I'd be interested in working on this. Thanks!

**Comment by matthyx** [comment]
@XDRAGON2002 I think this one is superseded by https://github.com/kubescape/kubescape/issues/1059

**Comment by XDRAGON2002** [comment]
@matthyx Oh, thanks for letting me know!

**Comment by craigbox** [comment]
They're actually two separate issues, though the fix for one might help with the other...

**Comment by XDRAGON2002** [comment]
@craigbox I'll go ahead and take this then.

**Comment by XDRAGON2002** [comment]
For wrapping we could simply add a utility function which when provided a string can format a string with `\n` like:
```
abcd abcd abcd -> function -> abcd\nabcd\nabcd
```

This is what the current table looks like, it's 164 chars in length, to be honest I'm not too sure exactly which part should be wrapped in here though?

```bash
+----------+----------------------------------------+------------------------------------+--------------------------------------------------------------------+
| SEVERITY |              CONTROL NAME              |                DOCS                |                        ASSISTED REMEDIATION                        |
+----------+----------------------------------------+------------------------------------+--------------------------------------------------------------------+
| High     | Resource limits                        | https://hub.armosec.io/docs/c-0009 | spec.containers[0].resources.limits.cpu=YOUR_VALUE                 |
|          |                                        |                                    | spec.containers[0].resources.limits.memory=YOUR_VALUE              |
+----------+----------------------------------------+------------------------------------+--------------------------------------------------------------------+
| Medium   | Allow privilege escalation             | https://hub.armosec.io/docs/c-0016 | spec.containers[0].securityContext.allowPrivilegeEscalation=false  |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | CVE-2022-0492-cgroups-container-escape | https://hub.armosec.io/docs/c-0086 | spec.containers[0].securityContext.runAsNonRoot=true               |
|          |                                        |                                    | spec.containers[0].securityContext.allowPrivilegeEscalation=false  |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | Configured liveness probe              | https://hub.armosec.io/docs/c-0056 | spec.containers[0].livenessProbe=YOUR_VALUE                        |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | Ingress and Egress blocked             | https://hub.armosec.io/docs/c-0030 |                                                                    |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | Linux hardening                        | https://hub.armosec.io/docs/c-0055 | spec.containers[0].securityContext.seccompProfile=YOUR_VALUE       |
|          |                                        |                                    | spec.containers[0].securityContext.seLinuxOptions=YOUR_VALUE       |
|          |                                        |                                    | spec.containers[0].securityContext.capabilities.drop[0]=YOUR_VALUE |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | Non-root containers                    | https://hub.armosec.io/docs/c-0013 | spec.containers[0].securityContext.runAsNonRoot=true               |
|          |                                        |                                    | spec.containers[0].securityContext.allowPrivilegeEscalation=false  |
+----------+----------------------------------------+------------------------------------+--------------------------------------------------------------------+
| Low      | Configured readiness probe             | https://hub.armosec.io/docs/c-0018 | spec.containers[0].readinessProbe=YOUR_VALUE                       |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | Immutable container filesystem         | https://hub.armosec.io/docs/c-0017 | spec.containers[0].securityContext.readOnlyRootFilesystem=true     |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | K8s common labels usage                | https://hub.armosec.io/docs/c-0077 | metadata.labels=YOUR_VALUE                                         |
+          +----------------------------------------+------------------------------------+                                                                    +
|          | Label usage for resources              | https://hub.armosec.io/docs/c-0076 |                                                                    |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | Naked PODs                             | https://hub.armosec.io/docs/c-0073 |                                                                    |
+          +----------------------------------------+------------------------------------+--------------------------------------------------------------------+
|          | Pods in default namespace              | https://hub.armosec.io/docs/c-0061 | metadata.namespace=YOUR_NAMESPACE                                  |
+----------+----------------------------------------+------------------------------------+--------------------------------------------------------------------+
```

**Comment by craigbox** [comment]
We're reinventing a web browser here.

Consider this GitHub screenshot:

<img width="826" alt="Screenshot 2023-07-18 at 10 01 42 AM" src="https://github.com/kubescape/kubescape/assets/132510/c164ef7b-1935-4f96-ab91-d4532ff554a7">

The trouble is, if someone has a terminal at ~80 characters, it won't scroll sideways, it will wrap like this.

<img width="714" alt="Screenshot 2023-07-18 at 10 02 34 AM" src="https://github.com/kubescape/kubescape/assets/132510/9d16a350-d448-4997-94ed-5cceb29ef4e8">

The answer is probably "detect narrow terminals and display the data differently".

**Comment by XDRAGON2002** [comment]
Ah I get it now, I had earlier thought we wanted to keep the same layout, instead we're truly going for a "responsive" feel (taking after your web browser analogy).

We could easily use [this](https://pkg.go.dev/github.com/kopoli/go-terminal-size#:~:text=GetSize%20gets%20the%20current%20terminal,it%20is%20not%20a%20terminal.) to detect the terminal width and render a different format.

I guess a block based approach is what might be best here, something like:
```bash
control_name_1
severity_1
docs_1
assisted_remediation_1
--------------------
control_name_2
...
...
```

This again would be in a table looking format for ease of visibility, but with column wise groupings instead of the traditional row wise ones (i.e. block based)
Thoughts?

**Comment by craigbox** [comment]
(This is the point where a product manager would probably build a mock-up, and look at what other projects are doing with presenting this kind of data.)

**Comment by XDRAGON2002** [comment]
Sounds good, I'll think this through a bit more and get in touch with some proper comparative samples. Thanks!

**Comment by XDRAGON2002** [comment]
@craigbox I took a look at both the CNCF landscape as well as some other methods via which this is being handled.

To be honest, I haven't been able to find any projects that ensure the 80 character width terminal size, this is because the 80 size is no longer the default and is considered "legacy" now by many.
Even Kubernetes itself doesn't support the 80 char limit, just run something like `kubectl auth can-i --list` as an example, the text simply wraps in a not so easy to read manner similar to what you've posted above in the screenshots.

Though looking outside of the CNCF landscape into how, many platforms handle this is via pivoting the table of sorts and instead of increasing it horizontally they scale it vertically, which looks like this:
![image](https://github.com/kubescape/kubescape/assets/81813720/5157518c-2623-458d-be0b-a5c9b1a0bfea)
![image](https://github.com/kubescape/kubescape/assets/81813720/ca5cbd30-fc8e-4fdf-821f-0975352ca6d3)

Which is pretty much the same approach as I had described above.

I'll also spin up an example as to how this would look like in the case of Kubescape for a better representation of the proposed solution.

Let me know what you think or if there are any better methods that I might have overlooked or not stumbled upon ;)

**Comment by XDRAGON2002** [comment]
@craigbox This is what it looks like for the `kubescape list controls` command:

![image](https://github.com/kubescape/kubescape/assets/81813720/57075308-2677-4a15-a425-fda6e7e75eea)

Though this is still not within the 80 char limit, but is an improvement from before in terms of space utilized, though as far as I think, we'll have to implement a custom wrapping functionality as mentioned earlier:
```
abcd abcd abcd -> function -> abcd\nabcd\nabcd
```
Wrapping functionality coupled with this suggested output format should ensure that everything remains within/extremely close to the 80 char limit.

Thoughts?

**Comment by craigbox** [comment]
That's much more manageable!
Did you do that by hand or did you change the code?
How does it look in other tables, e.g. the verbose scan output?

**Comment by XDRAGON2002** [comment]
Changed the code a bit to achieve this formatting instead, much easier to direct hack on the codebase than to do it by hand ;)

As another example, I'll just go ahead and make changes to the verbose summary table as well.

**Comment by XDRAGON2002** [comment]
@craigbox 
Here's what output for `kubescape scan resource.yaml -v` looks like:

![image](https://github.com/kubescape/kubescape/assets/81813720/ff4c377d-7096-4b6a-88f5-869a386b9f96)

I hope it looks neat enough ;)

**Comment by XDRAGON2002** [comment]
@craigbox another thing I'd like to clarify, do we want the format to be changed from the original format to this open automatically via somehow checking the current terminal width or should be provide a user flag instead? If so what might it be called `--short`?
